//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("OrganizationModel", "FK_tbl_Emp_tbl_Dept", "tbl_Dept", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EntityFrameWork.App_Code.tbl_Dept), "tbl_Emp", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFrameWork.App_Code.tbl_Emp), true)]

#endregion

namespace EntityFrameWork.App_Code
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OrganizationDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OrganizationDBEntities object using the connection string found in the 'OrganizationDBEntities' section of the application configuration file.
        /// </summary>
        public OrganizationDBEntities() : base("name=OrganizationDBEntities", "OrganizationDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OrganizationDBEntities object.
        /// </summary>
        public OrganizationDBEntities(string connectionString) : base(connectionString, "OrganizationDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OrganizationDBEntities object.
        /// </summary>
        public OrganizationDBEntities(EntityConnection connection) : base(connection, "OrganizationDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Dept> tbl_Dept
        {
            get
            {
                if ((_tbl_Dept == null))
                {
                    _tbl_Dept = base.CreateObjectSet<tbl_Dept>("tbl_Dept");
                }
                return _tbl_Dept;
            }
        }
        private ObjectSet<tbl_Dept> _tbl_Dept;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Emp> tbl_Emp
        {
            get
            {
                if ((_tbl_Emp == null))
                {
                    _tbl_Emp = base.CreateObjectSet<tbl_Emp>("tbl_Emp");
                }
                return _tbl_Emp;
            }
        }
        private ObjectSet<tbl_Emp> _tbl_Emp;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Dept EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Dept(tbl_Dept tbl_Dept)
        {
            base.AddObject("tbl_Dept", tbl_Dept);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Emp EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Emp(tbl_Emp tbl_Emp)
        {
            base.AddObject("tbl_Emp", tbl_Emp);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OrganizationModel", Name="tbl_Dept")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Dept : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Dept object.
        /// </summary>
        /// <param name="deptId">Initial value of the DeptId property.</param>
        /// <param name="deptName">Initial value of the DeptName property.</param>
        /// <param name="deptHOD">Initial value of the DeptHOD property.</param>
        public static tbl_Dept Createtbl_Dept(global::System.Int32 deptId, global::System.String deptName, global::System.String deptHOD)
        {
            tbl_Dept tbl_Dept = new tbl_Dept();
            tbl_Dept.DeptId = deptId;
            tbl_Dept.DeptName = deptName;
            tbl_Dept.DeptHOD = deptHOD;
            return tbl_Dept;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DeptId
        {
            get
            {
                return _DeptId;
            }
            set
            {
                if (_DeptId != value)
                {
                    OnDeptIdChanging(value);
                    ReportPropertyChanging("DeptId");
                    _DeptId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DeptId");
                    OnDeptIdChanged();
                }
            }
        }
        private global::System.Int32 _DeptId;
        partial void OnDeptIdChanging(global::System.Int32 value);
        partial void OnDeptIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DeptName
        {
            get
            {
                return _DeptName;
            }
            set
            {
                OnDeptNameChanging(value);
                ReportPropertyChanging("DeptName");
                _DeptName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DeptName");
                OnDeptNameChanged();
            }
        }
        private global::System.String _DeptName;
        partial void OnDeptNameChanging(global::System.String value);
        partial void OnDeptNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DeptHOD
        {
            get
            {
                return _DeptHOD;
            }
            set
            {
                OnDeptHODChanging(value);
                ReportPropertyChanging("DeptHOD");
                _DeptHOD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DeptHOD");
                OnDeptHODChanged();
            }
        }
        private global::System.String _DeptHOD;
        partial void OnDeptHODChanging(global::System.String value);
        partial void OnDeptHODChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OrganizationModel", "FK_tbl_Emp_tbl_Dept", "tbl_Emp")]
        public EntityCollection<tbl_Emp> tbl_Emp
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_Emp>("OrganizationModel.FK_tbl_Emp_tbl_Dept", "tbl_Emp");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_Emp>("OrganizationModel.FK_tbl_Emp_tbl_Dept", "tbl_Emp", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OrganizationModel", Name="tbl_Emp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Emp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Emp object.
        /// </summary>
        /// <param name="empId">Initial value of the EmpId property.</param>
        /// <param name="empName">Initial value of the EmpName property.</param>
        /// <param name="empSalary">Initial value of the EmpSalary property.</param>
        /// <param name="empGender">Initial value of the EmpGender property.</param>
        /// <param name="empDOB">Initial value of the EmpDOB property.</param>
        public static tbl_Emp Createtbl_Emp(global::System.Int32 empId, global::System.String empName, global::System.Double empSalary, global::System.String empGender, global::System.DateTime empDOB)
        {
            tbl_Emp tbl_Emp = new tbl_Emp();
            tbl_Emp.EmpId = empId;
            tbl_Emp.EmpName = empName;
            tbl_Emp.EmpSalary = empSalary;
            tbl_Emp.EmpGender = empGender;
            tbl_Emp.EmpDOB = empDOB;
            return tbl_Emp;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmpId
        {
            get
            {
                return _EmpId;
            }
            set
            {
                if (_EmpId != value)
                {
                    OnEmpIdChanging(value);
                    ReportPropertyChanging("EmpId");
                    _EmpId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmpId");
                    OnEmpIdChanged();
                }
            }
        }
        private global::System.Int32 _EmpId;
        partial void OnEmpIdChanging(global::System.Int32 value);
        partial void OnEmpIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmpName
        {
            get
            {
                return _EmpName;
            }
            set
            {
                OnEmpNameChanging(value);
                ReportPropertyChanging("EmpName");
                _EmpName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmpName");
                OnEmpNameChanged();
            }
        }
        private global::System.String _EmpName;
        partial void OnEmpNameChanging(global::System.String value);
        partial void OnEmpNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double EmpSalary
        {
            get
            {
                return _EmpSalary;
            }
            set
            {
                OnEmpSalaryChanging(value);
                ReportPropertyChanging("EmpSalary");
                _EmpSalary = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmpSalary");
                OnEmpSalaryChanged();
            }
        }
        private global::System.Double _EmpSalary;
        partial void OnEmpSalaryChanging(global::System.Double value);
        partial void OnEmpSalaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmpGender
        {
            get
            {
                return _EmpGender;
            }
            set
            {
                OnEmpGenderChanging(value);
                ReportPropertyChanging("EmpGender");
                _EmpGender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmpGender");
                OnEmpGenderChanged();
            }
        }
        private global::System.String _EmpGender;
        partial void OnEmpGenderChanging(global::System.String value);
        partial void OnEmpGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EmpDOB
        {
            get
            {
                return _EmpDOB;
            }
            set
            {
                OnEmpDOBChanging(value);
                ReportPropertyChanging("EmpDOB");
                _EmpDOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmpDOB");
                OnEmpDOBChanged();
            }
        }
        private global::System.DateTime _EmpDOB;
        partial void OnEmpDOBChanging(global::System.DateTime value);
        partial void OnEmpDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailId
        {
            get
            {
                return _EmailId;
            }
            set
            {
                OnEmailIdChanging(value);
                ReportPropertyChanging("EmailId");
                _EmailId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailId");
                OnEmailIdChanged();
            }
        }
        private global::System.String _EmailId;
        partial void OnEmailIdChanging(global::System.String value);
        partial void OnEmailIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DeptId
        {
            get
            {
                return _DeptId;
            }
            set
            {
                OnDeptIdChanging(value);
                ReportPropertyChanging("DeptId");
                _DeptId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeptId");
                OnDeptIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DeptId;
        partial void OnDeptIdChanging(Nullable<global::System.Int32> value);
        partial void OnDeptIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OrganizationModel", "FK_tbl_Emp_tbl_Dept", "tbl_Dept")]
        public tbl_Dept tbl_Dept
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Dept>("OrganizationModel.FK_tbl_Emp_tbl_Dept", "tbl_Dept").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Dept>("OrganizationModel.FK_tbl_Emp_tbl_Dept", "tbl_Dept").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Dept> tbl_DeptReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Dept>("OrganizationModel.FK_tbl_Emp_tbl_Dept", "tbl_Dept");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Dept>("OrganizationModel.FK_tbl_Emp_tbl_Dept", "tbl_Dept", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
